### ISSUE TITLE
Add `jsonld -h` as an alias for `jsonld -?`

### ISSUE THREAD

**Issue by bendiken** [ruby-rdf/json-ld#21]
The `-h` command-line option might perhaps do something more useful than the current output:

    $ jsonld -h
    /usr/bin/jsonld: invalid option -- h
    /usr/lib/ruby/2.0.0/getoptlong.rb:394:in `set_error': invalid option -- h (GetoptLong::InvalidOption)
    	from /usr/lib/ruby/2.0.0/getoptlong.rb:571:in `get'
    	from /usr/lib/ruby/2.0.0/getoptlong.rb:602:in `block in each'
    	from /usr/lib/ruby/2.0.0/getoptlong.rb:601:in `loop'
    	from /usr/lib/ruby/2.0.0/getoptlong.rb:601:in `each'
    	from bin/jsonld:122:in `<top (required)>'
    	from /usr/bin/jsonld:23:in `load'
    	from /usr/bin/jsonld:23:in `<main>'

**Comment by bendiken** [comment]
In the same vein, supporting `jsonld --version` (short form `-V`) might also be a good idea.

**Comment by gkellogg** [comment]
Closed in favor of the more comprehensive `rdf` command.
