### ISSUE TITLE
Correct the RDF.rb version dependency

### ISSUE THREAD

**Issue by bendiken** [ruby-rdf/json-ld#22]
It'd probably be a good idea to tighten the RDF.rb version dependency a bit on the JSON::LD 1.1.x branch, as right now it will happily pull in RDF.rb 1.99.x on a machine that doesn't already have it installed:

    $ sudo gem install json-ld -v 1.1.11
    Fetching: link_header-0.0.8.gem (100%)
    Fetching: rdf-1.99.0.gem (100%)
    Fetching: multi_json-1.11.2.gem (100%)
    Fetching: json-ld-1.1.11.gem (100%)
    Successfully installed link_header-0.0.8
    Successfully installed rdf-1.99.0
    Successfully installed multi_json-1.11.2
    Successfully installed json-ld-1.1.11
    4 gems installed

This means that in normal use, users will see tons of deprecation notices for what ought to be a production release of the JSON::LD library and CLI utility.

**Comment by gkellogg** [comment]
I suppose the right thing is to release this as json-ld 1.99.0, and yank 1.1.11. I'll check other gems as well.

**Comment by bendiken** [comment]
Alternatively, couldn't the gemspec for the 1.1.x branch specify "< 1.99" in the dependency? That is, it'd be good to keep a production version around, as 1.99 can't be considered that given the voluminous deprecation warnings.

**Comment by gkellogg** [comment]
No, it was updated to use `graph_name`, which is in 1.99.

**Comment by gkellogg** [comment]
Released 1.1.11.1 with RDF versions < 1.99

**Comment by bendiken** [comment]
Thanks @gkellogg, the 1.1.11.1 version works great (doesn't output warnings).
