### ISSUE TITLE
Some JSON-LD Documents are Pathologically Slow

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/json-ld#25]
An example is this [LDP Container with ~6,000 member objects](https://gist.github.com/tpendragon/3438dff0b30dfa549599#file-content-jsonld). The [benchmark](https://gist.github.com/tpendragon/3438dff0b30dfa549599#file-ruby-rb-L1) included in the gist shows a total time of __32.45 seconds__ to parse the document via `RDF::Graph#load`. Using `RDF::Reader#open` is similarly slow. Based on behavior I've seen with similarly sized documents, I'm expecting results closer to the 1 second range.

I haven't tracked down a specific reason for this, yet. One clue might be that this graph also seems unusually slow to parse as NTriples and Turtle in 1.99.1, but [not in 2.0.0.beta1](https://gist.github.com/tpendragon/3438dff0b30dfa549599#gistcomment-1709517). My suspicion is that it has to do with the very high cardinality of the `<> ldp:contains ?o` pattern.

Thanks to @tpendragon for raising this issue.

**Comment by gkellogg** [comment]
It might be worth parsing to a sink, rather than a graph; that will cut out graph insert times as being a culprit. JSON-LD doesn't get nice with large graphs, but that's mostly a writing problem, not a parsing problem.

I believe the etc/parse script can be used with --format none to simply count triples, rather than insert them. Give that a shot.

**Comment by gkellogg** [comment]
No, still takes 30 seconds on my MacBook Pro:

```bash
[json-ld] script/parse --format none example-files/pendragon.jsonld 
Parsed 6021 statements in 30.620508 seconds @ 196.63292326828804 statements/second.
```

On thing I explored is to use the `:expanded` option to avoid expanding the input first, but that has no effect. My guess is that it's in the flattening logic. Adding a `:flattened` option to avoid flattening might help, and that algorithm could possibly be improved as well.

**Comment by no-reply** [comment]
Re: `:flatten`; I tried this:

```ruby
Benchmark.measure { JSON::LD::Reader.new(File.open("../rdf-ldp/content.jsonld", flatten: false)).count }
=> #<Benchmark::Tms:0x0055dc496c8420
 @cstime=0.0,
 @cutime=0.0,
 @label="",
 @real=31.042243408,
 @stime=0.020000000000000018,
 @total=31.069999999999983,
 @utime=31.049999999999983>
```

**Comment by gkellogg** [comment]
Yeah, there is no `:flatten` option. The `toRdf` algorithm creates a node map and then outputs statements from that map. The node map is also used to flatten, so a `:flatten false` option would need to do something different.

It might be better to just re-write the `toRdf` algorithm to not flatten first, although there was clearly a reason this was specified. Simply using expanded JSON-LD and traversing through it may work, but corner cases need to be checked. Definitely no quick fix.

**Comment by gkellogg** [comment]
Easy enough to re-implement this. New version runs in < 1 second.
