### ISSUE TITLE
Generating Graph from JSON-LD surprisingly slow?

### ISSUE THREAD

**Issue by njh** [ruby-rdf/json-ld#29]
Hello,

I have been making a website that lists the available Arduino libraries:
http://www.arduinolibraries.info/

I recently added schema.org structured data in the form of JSON-LD, which is embedded in page, and also available as a JSON document:
http://www.arduinolibraries.info/libraries/ether-sia
http://www.arduinolibraries.info/libraries/ether-sia.json

For fun I thought I would also generate Turtle, from the JSON-LD. But have found it to be surprisingly slow - several seconds, for a very small number of triples.

Code:
https://github.com/njh/arduino-libraries/commit/24e8f9dbb64e6fa2d9a6f73a43c52453cecbe161#diff-55ef48a181f10f92f33bc40126b4378cR38

Do you have any idea why?
Is there a more efficient way of doing it?

The whole site used to generated in around 2 seconds, now it takes longer than that for one document.

nick.

**Comment by gkellogg** [comment]
If it's a large file (many subjects), Turtle serializer may be slow, as it tries to order things. There's a streaming mode which should be pretty fast.

The writer could conceivably look at the dataset size to switch between, but as it's a streaming interface, this isn't to easy. Try using the streaming turtle writer and see how that works.

But, you've got me thinking of other ways we might detect this when writing; I'll look into it.

(Should be on the rdf-turtle repo, though).

**Comment by njh** [comment]
Hi Gregg!

I separated out the JSON-LD parsing from the Turtle serialising and it was the JSON-LD part that took the time, not the Turtle serialisation.

There are 2 subjects and 11 triples, so the Turtle serialiser shouldn't be slow anyway.

If it isn't anything obvious, then I will dig a bit deeper tomorrow. 

nick.

**Comment by gkellogg** [comment]
Perhaps it's context fetch time, try inclining those terms you need to see.

**Comment by njh** [comment]
Yup, it is because it is  repeatedly downloading the context.

I tried adding 'restclient/components' but weirdly got an error loading the context:
> rest-client-2.0.0/lib/restclient/abstract_response.rb:20:in `history': loading remote context failed: http://schema.org/ (JSON::LD::JsonLdError::LoadingRemoteContextFailed)

I will try being more explicit with the context.

**Comment by njh** [comment]
I have implemented a rake tasks which pre-fetches the schema.org context file and then injects it into the JSON-LD before generating the statements:
https://github.com/njh/arduino-libraries/commit/98e854fd36a1dff289c4f93a7bfd7468892a4ad3

It speeds it up a lot, not having to go to the network every time.

* Generating an array of statements from the JSON-LD takes 0.28 seconds per file.
* Writing the turtle from the array of statements takes less than 0.01 seconds per file
* So converting ~614 JSON-LED files to Turtle takes around 133 seconds
* Generating ~1000 HTML files from ERB templates takes around 1.5 seconds

So I am still quite surprised by how slow JSON-LD parsing to RDF statements is.
Is there anything else I can do to speed it up?

**Comment by gkellogg** [comment]
If you maintain the executable state, the gem caches the context in memory. Otherwise, you can implement your own remote loader, which will be used for loading contexts.

Regarding other processing costs: the input must be expanded before statements can be generates. I did just fix a bug where sorting was not turned off when expanding, which might have something to do with it. Are you using the develop branch? JSON-LD algorithms definitely impose substantial compute burdens.

There is probably some more optimization that can be done. Maybe you're interested in looking into it more?

**Comment by gkellogg** [comment]
Processing the Schema.org contex, even when in memory, will take some time too. Processing it, and loading a cooked version from YAML, say, might also speed up. Problem is not tightly building in a Schema.org version dependency, but a meta-gem might do this. I could see some hooks in context loading that might help support this.

To test, you might whittle down your inline context to the minimum and see how that affects processing. Or try processing JSON in expanded mode (can be signaled with an option, I believe) to isolate the computing cost m

**Comment by njh** [comment]
Gah, looks like specifying a git branch in a Gemfile is currently broken bundler/bundler#4659

**Comment by gkellogg** [comment]
It seems to work for me, look at https://github.com/ruby-rdf/json-ld/blob/develop/Gemfile#L4 for example.

I'm working on a way to look for a pre-loaded context, which would allow the meta-gem I described. It would also be useful with this gem, if you pre-loaded it as part of your library; probably requires a vocabulary URL to class/constant mapping be passed in. Should dramatically improve use for schema.org.

**Comment by njh** [comment]
Fixed my git branch problem - it was because I was specifying a version of ruby which conflicted with the ruby specification in the gems I was requiring.


Got a bit hack but started breaking down API#toRdf to work out where the time is being spent:

```ruby
  Benchmark.bm do |x|
    x.report("new API") { @api = JSON::LD::API.new(jsonld, nil, {}) }
    x.report("expand") {
      @expanded = @api.expand(@api.value, nil, @api.context, ordered: false)
      @expanded = [@expanded].compact unless @expanded.is_a?(Array)
    }

    x.report("new API 2") { @api2 = JSON::LD::API.new(@expanded, nil) }
    @statements = []
    @statements.extend(RDF::Enumerable)
    
    x.report("toRdf") {
      @expanded.each do |node|
        @api2.item_to_rdf(node) do |statement|
          @statements << statement
        end
      end
    }

    x.report("turtle") {
    RDF::Turtle::Writer.open("public/libraries/#{key}.ttl") do |writer|
      writer << @statements
    end
    }
  end
```

Typical result:
```
       user     system      total        real
new API  0.100000   0.000000   0.100000 (  0.104639)
expand  0.100000   0.010000   0.110000 (  0.099353)
new API 2  0.000000   0.000000   0.000000 (  0.000038)
toRdf  0.000000   0.000000   0.000000 (  0.000493)
turtle  0.000000   0.000000   0.000000 (  0.004380)
```

So most of the time is split pretty much equality between the first API.new (which I guess is evaluating the context) and @api.expand().

The second API.new, item_to_rdf and Turtle writing take almost no time.

**Comment by gkellogg** [comment]
Yes, I have a similar bench-mark. Having a general utility to save cooked contexts will be useful, and make it easy for implementations to improve their own use cases.

**Comment by njh** [comment]
I have broken out ruby-prof and got the following results (for a single graph):
* https://www.aelius.com/njh/tmp/json-ld/ruby-prof-stack.html
* https://www.aelius.com/njh/tmp/json-ld/ruby-prof-flat.txt
* https://www.aelius.com/njh/tmp/json-ld/ruby-prof.html

As an experiment I tried commenting out all the include RDF::Util::Logger, log_*() calls.
I was surprised to find that it nearly halved the execution time.

I don't have any experience of reading ruby-prof - so not sure the best ways to pick out other performance improvements.

**Comment by gkellogg** [comment]
The logger can be disabled by passing in `logger: false`; it defaults to STDERR. Reading profiles is pretty difficult, and deciding what can be improved. Using the new support I added should help.

For testing, I created a file in `example-files/schema-context.rb`, which you can include, which should have the effect of not loading the context remotely. I expect that will make a substantial difference, but haven't tested myself yet. Eventually, I'll put that into a json-ld-schema gem, which can then be used instead of the json-ld gem to get that effect. It will need to be updated with every schema.org release, but that might be able to be automated eventually.

**Comment by gkellogg** [comment]
The profile shows it's spending 83% of it's time in context parsing, which should go away. It's also spending > 20% of its time in logging, and I think the best thing now is to simply remove most of these, as they were more important in initial development.

**Comment by gkellogg** [comment]
@njh: try using https://github.com/ruby-rdf/json-ld-preloaded, which preloads several contexts. It can simply be used instead of `require "json/ld"` => `require "json/ld/preloaded"`.

If this is adequate, I'll release both that, and the updated json-ld gem. The distiller and linter will benefit quite a bit too.

**Comment by njh** [comment]
Performance after switching to "json/ld/preloaded":

```
       user     system      total        real
new API  0.000000   0.010000   0.010000 (  0.001827)
expand  0.000000   0.000000   0.000000 (  0.003138)
new API 2  0.000000   0.000000   0.000000 (  0.000045)
toRdf  0.000000   0.000000   0.000000 (  0.000430)
turtle  0.010000   0.000000   0.010000 (  0.003814)
```

So a significant improvement :)

My total run time for converting 618 libraries from JSON to Turtle (including starting Ruby etc) is now 4.788s. Much better. Would be super-happy if it was more like 1.6 seconds, like the HTML ;-)

**Comment by njh** [comment]
I am not totally convinced by the `json-ld-preloaded` gem - partly because of having to re-publish it so frequently?  Although it might be good for applications other than mine.

Because in my application, I have to pre-download other JSON files - it seems fairly straightforward to do the same for the schema.org context.

This is working for me, without using json-ld-preloaded:
```ruby
JSON::LD::Context.add_preloaded(
  'http://schema.org/',
  JSON::LD::Context.new.parse(
    JSON.parse(
      File.read('schema_org_context.json')
    )['@context']
  )
)
```

Can it be any more concise?

**Comment by gkellogg** [comment]
Contexts don't actually change that much, and schema.org releases aren't really that frequent. Even so, the rdf-vocab gem needs similar frequency of releases. For most purposes, it shouldn't be an issue.

I'm not sure why it's any different for json-ld-preloaded and your own application; one or the other would need to be updated, and a new call to `add_preloaded` will override an existing preloaded entry.

Try:

```json
JSON::LD::Context.add_preloaded(
  'http://schema.org/',
  JSON::LD::Context.new.parse('schema_org_context.json')
)
```

**Comment by njh** [comment]
That works great, thanks.

`schema_org_context.json` isn't distributed with my application, it is downloaded in my Rake script at the start of each site re-build.
