### ISSUE TITLE
Framing returns a blank @graph.

### ISSUE THREAD

**Issue by workergnome** [ruby-rdf/json-ld#30]
When I try and frame a document, I'm getting a blank graph returned.

``` ruby

require 'linkeddata'

unframed_json = JSON.parse '[
  {
    "@id": "http://vocab.getty.edu/ulan/500115403",
    "http://xmlns.com/foaf/0.1/focus": [
      {
        "@id": "http://vocab.getty.edu/ulan/500115403-agent"
      }
    ],
    "http://www.w3.org/2004/02/skos/core#prefLabel": [
      {
        "@value": "Couture, Thomas"
      }
    ],
    "http://www.w3.org/2004/02/skos/core#inScheme": [
      {
        "@id": "http://vocab.getty.edu/ulan/"
      }
    ],
    "http://schema.org/url": [
      {
        "@id": "http://www.getty.edu/vow/ULANFullDisplay?find=&role=&nation=&subjectid=500115403"
      }
    ]
  }
]'

frame = JSON.parse '{
  "@explicit": true,
  "@context": {
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "foaf": "http://xmlns.com/foaf/0.1/",
    "schema": "http://schema.org/",
    "label": "skos:prefLabel",
    "id": "@id",
    "source": {
      "@id": "skos:inScheme",
      "@type": "@id"
    },
    "agent": {
      "@id": "foaf:focus",
      "@type": "@id"
    },
    "website": {
      "@id": "schema:url",
      "@type": "@id"
    }
  },
  "label": {},
  "id": {},
  "source": {},
  "agent": {},
  "website": {}
}'

puts JSON::LD::API.frame(unframed_json, frame)
```

returns

```
{
 "@context"=>{
  "skos"=>"http://www.w3.org/2004/02/skos/core#", 
  "foaf"=>"http://xmlns.com/foaf/0.1/", 
  "schema"=>"http://schema.org/", 
  "label"=>"skos:prefLabel", 
  "id"=>"@id",
   "source"=>{"@id"=>"skos:inScheme", "@type"=>"@id"}, 
   "agent"=>{"@id"=>"foaf:focus", "@type"=>"@id"}, 
   "website"=>{"@id"=>"schema:url", "@type"=>"@id"}
 }, 
 "@graph"=>[]
}
```

But when I put the same JSON into the JSON-LD Playground, I get the values I expect:

[permalink to Playground](http://json-ld.org/playground/#startTab=tab-framed&json-ld=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500115403%22%2C%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2Ffocus%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500115403-agent%22%7D%5D%2C%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%22%3A%5B%7B%22%40value%22%3A%22Couture%2C%20Thomas%22%7D%5D%2C%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23inScheme%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Fulan%2F%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fwww.getty.edu%2Fvow%2FULANFullDisplay%3Ffind%3D%26role%3D%26nation%3D%26subjectid%3D500115403%22%7D%5D%7D%5D&frame=%7B%22%40explicit%22%3Atrue%2C%22%40context%22%3A%7B%22skos%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%22%2C%22foaf%22%3A%22http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%22%2C%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22label%22%3A%22skos%3AprefLabel%22%2C%22id%22%3A%22%40id%22%2C%22source%22%3A%7B%22%40id%22%3A%22skos%3AinScheme%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22agent%22%3A%7B%22%40id%22%3A%22foaf%3Afocus%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22website%22%3A%7B%22%40id%22%3A%22schema%3Aurl%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22label%22%3A%7B%7D%2C%22id%22%3A%7B%7D%2C%22source%22%3A%7B%7D%2C%22agent%22%3A%7B%7D%2C%22website%22%3A%7B%7D%7D&context=%7B%7D)

**Comment by gkellogg** [comment]
It looks like there's a difference in the implementations when @id is included in the frame. In your example, if you remove `"id": {},`, you should get the output you expect.

In the current draft, the behavior of `@id` is undefined. However, in a branch being considered to be merged (which you can see [here](https://rawgit.com/json-ld/json-ld.org/issue-110-frame-matching/spec/latest/json-ld-framing/index.html)), it is expected to be one or more IRI or BNodes, which are used to match. However, it seems consistent with other matching to interpret `{}` as a wild-card, so this is likely a bug in both the new spec and my implementation.

In the mean time, try just removing `id` from the frame.

**Comment by workergnome** [comment]
Thank you.  That appears to be exactly what is going on, and your work-around solves my immediate problem.

**Comment by gkellogg** [comment]
This should be fully supported now.
