### ISSUE TITLE
NameError: uninitialized constant JSON::LD::Writer

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/json-ld#34]
```
 NameError: uninitialized constant JSON::LD::Writer Did you mean? JSON::LD::Writer

    [GEM_ROOT]/gems/json-ld-2.1.2/lib/json/ld/format.rb:30 :in `block in <class:Format>`

    [GEM_ROOT]/gems/rdf-2.2.3/lib/rdf/writer.rb:106 :in `block in format`
    [GEM_ROOT]/gems/rdf-2.2.3/lib/rdf/format.rb:55 :in `each`
    [GEM_ROOT]/gems/rdf-2.2.3/lib/rdf/format.rb:55 :in `each`
    [GEM_ROOT]/gems/rdf-2.2.3/lib/rdf/writer.rb:105 :in `format`
    [GEM_ROOT]/gems/rdf-2.2.3/lib/rdf/writer.rb:94 :in `for`
    [GEM_ROOT]/gems/rdf-2.2.3/lib/rdf/mixin/enumerable.rb:787 :in `respond_to_missing?`
    [GEM_ROOT]/gems/rdf-2.2.3/lib/rdf/mixin/enumerable.rb:444 :in `Array`
    [GEM_ROOT]/gems/rdf-2.2.3/lib/rdf/mixin/enumerable.rb:444 :in `objects`
```

**Comment by jcoyne** [comment]
I don't know what to make of this.  Constants loaded in different threads perhaps?

**Comment by jcoyne** [comment]
Is this because autoload is not thread safe? 
https://github.com/ruby-rdf/json-ld/blob/f830eca03ac52a2ccc207dc448ad33c93a81c74e/lib/json/ld.rb#L36

**Comment by gkellogg** [comment]
Hi @jcoyne, sorry I've been under the weather and offline for a bit. Does this happen all the time, or just sometimes? The message is pretty odd, as it suggests exactly the same constant it finds missing. `RDF::Writer.for` does look at all formats to find something that includes a writer that matches for the format requirements (content-type, file-extension, format symbol). All formats are defined when their gem is required to allow for this, but readers and writers are autoloaded, so as not to pollute the runtime and save time.

It's possible that you were running different things that overlapped, triggering the autoload in one thread and hitting the same code in a second before the load had completed, but I would think this would just try to load the code twice, and result in the `Writer` class constant becoming defined.

Not sure what else to do, but a repeatable test case might help narrow this down. As a workaround, you might start by causing all loaders for formats your interested in to be loaded when you start up using something like:

```ruby
RDF::Writer.each {|w|}
```

**Comment by jcoyne** [comment]
No trouble @gkellogg I hope you're getting better.  I was seeing this only on an extremely overloaded system.  I suspect there might be a bug in ruby autoload triggered when the system is resource starved.
