### ISSUE TITLE
Problem with framing and bases

### ISSUE THREAD

**Issue by workergnome** [ruby-rdf/json-ld#35]
When using the `linkeddata`  gem (v. 2.2.0), when I create a frame with a context that contains both a link to an external context and an inline context, framing fails.

However, if I explicitly add a base, framing works.  Have I misinterpreted the spec again, or is this an actual bug?  It appears to work on the JSON-LD Playground: [See this permalink](http://json-ld.org/playground/#startTab=tab-framed&json-ld=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fwww.museum.com%2Ffish%22%2C%22%40type%22%3A%5B%22http%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2FE55_Type%22%5D%7D%5D&frame=%7B%22%40context%22%3A%5B%22https%3A%2F%2Flinked.art%2Fns%2Fcontext%2F1%2Ffull.jsonld%22%2C%7B%22crm%22%3A%22http%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%22%7D%5D%7D).

**Failing Example**

```ruby
require 'linkeddata'

graph = RDF::Graph.new
graph << [RDF::URI("http://www.museum.com/fish"), 
          RDF.type, 
          RDF::URI("http://www.cidoc-crm.org/cidoc-crm/E55_Type")]

unframed_json = JSON::LD::API::fromRdf(graph)


# Using this frame:
frame = {
  "@context"=> [
    "https://linked.art/ns/context/1/full.jsonld",
    {"crm" => "http://www.cidoc-crm.org/cidoc-crm/"}
  ]
}

# This works
puts JSON::LD::API.frame(unframed_json, frame, base: "http://www.example.com")

# But this doesn't.
begin
  puts JSON::LD::API.frame(unframed_json, frame)
rescue JSON::LD::JsonLdError::InvalidBaseIRI => e
  puts "This doesn't work: #{e}"
end


# But using this frame:
frame = {
  "@context"=> [
    {"crm" => "http://www.cidoc-crm.org/cidoc-crm/"}
  ]
}
# Both of these work
puts JSON::LD::API.frame(unframed_json, frame, base: "http://www.example.com")
puts JSON::LD::API.frame(unframed_json, frame)

```

**Comment by gkellogg** [comment]
It seems this was resolved somewhere before the release of 2.1.3.
