### ISSUE TITLE
@base not working for integer value in JSON

### ISSUE THREAD

**Issue by kevinxin90** [ruby-rdf/json-ld#39]
Hi, I was testing the JSON-LD 1.1 ruby client. And I found if the value of a json_doc is an integer, the @base parameter wouldn't work.
e.g.  (the value of "_id" is integer here)
```json
{
"@context": {
   "@version": 1.1,
   "_id": {
       "@type": "@id",
       "@id": "http://www.w3.org/2004/02/skos/core#exactMatch",
       "@context": {
             "@base": "http://identifiers.org/hgnc.symbol/"
        }
   }
},
"@id": "http://mygene.info/1017",
"_id": 1017
}
```
This wouldn't convert the value of "_id", the compacted output is like follows:
```json
{
  "@id": "http://mygene.info/1017",
  "http://www.w3.org/2004/02/skos/core#exactMatch": {
    "@id": "1017"
  }
}
```
However, if I change the value of "_id" into "1017", it works.
e.g.
```json
{
"@context": {
   "@version": 1.1,
   "_id": {
       "@type": "@id",
       "@id": "http://www.w3.org/2004/02/skos/core#exactMatch",
       "@context": {
             "@base": "http://identifiers.org/hgnc.symbol/"
        }
   }
},
"@id": "http://mygene.info/1017",
"_id": "1017"
}
```
Here, I get what I want
e.g. 
```json
{
  "@id": "http://mygene.info/1017",
  "http://www.w3.org/2004/02/skos/core#exactMatch": {
    "@id": "http://identifiers.org/hgnc.symbol/1017"
  }
}
```
I'm wondering is this a bug in the client?

Thanks!

**Comment by gkellogg** [comment]
I don't believe the spec has ever supported this..you might send out feelers on public-linked-json@w3.org, but I'm afraid I won't be able to respond in any substantive way for a couple of weeks.
