### ISSUE TITLE
Tutorial or example ?

### ISSUE THREAD

**Issue by Tioneb12** [ruby-rdf/json-ld#48]
Where can I find a complete tutorial or example for newbie (step by step) who explain how can I use your gem ?

Thanks

**Comment by gkellogg** [comment]
I have no tutorial specifically for using the json-ld Gem, but there are many examples on the README, and in the more detailed documentation which you can find [here]().

In addition to the standard RDF reader/writer interface implemented, the gem supports the [JSON-LD API](https://www.w3.org/TR/json-ld11-api/) and [JSON-LD Framing](https://www.w3.org/TR/json-ld11-framing/), which also have examples of use.

If there's something spec that you're looking for that isn't addressed in the documentation or specs, let me know and I'll see if I can improve the documentation.

**Comment by dsisnero** [comment]
how would you load the triples from a html page that has json-ld in the header

**Comment by gkellogg** [comment]
The JSON-LD gem will natively retrieve JSON-LD from HTML via the various API methods. To work best, you should also have the Nokogiri gem available. You can also extract JSON-LD from HTML using the reader interface, to create an RDF Repository.

There's an example in the [README](https://ruby-rdf.github.io/json-ld/#label-Turn+JSON-LD+into+RDF+-28Turtle-29) on doing just this from JSON-LD source. This would be essentially the same thing for HTML

For example:

```ruby
require 'json/ld'
require 'nokogiri'

File.open("example.html") do |f|
  graph = RDF::Graph.new << JSON::LD::API.toRdf(f, extractAllScripts: true)
end
```

Or, using the Reader interface:

```ruby
graph = RDF::Graph.new << JSON::LD::Reader.open("example.html", extractAllScripts: true)
```
