### ISSUE TITLE
@id in JSON LD prevent matching

### ISSUE THREAD

**Issue by typhoon2099** [ruby-rdf/json-ld#50]
I'm using SPARQL to query some JSON-LD, but for some reason the itemListElement of an ItemList is not being returned. It looks to be related to the @id property being present on the Product
Here's a query to match everything:
```
PREFIX rsp: <http://rubygems.org/gems/sparql#>
      PREFIX s: <http://schema.org/>

      SELECT *
      WHERE {
        ?s ?p ?o
      }
```
Here's my JSON-LD
```
  {
    "@context": "http://schema.org",
    "@type": "ItemList",
    "name": null,
    "description": null,
    "numberOfItems": 4,
    "itemListOrder": "Relevance",
    "url": "https://www.example.com",
    "itemListElement": [
      {
        "@type": "Product",
        "@id": "123456",
        "name": "Product Name",
        "sku": "product-name",
        "url": "https://www.example.com/product",
        "image": "https://www.example.com/image.jpg",
        "position": 1,
        "potentialAction": {
          "@type": "Action",
          "name": "Add to cart"
        }
      }
    ]
  }
```
Here's the list of solutions:
```
{:s=>#<RDF::Node:0x2afcccbc4960(_:b1)>, :p=>#<RDF::Vocabulary::Term:0x2afccb3fb658 ID:http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, :o=>#<RDF::URI:0x2afcccbc4938 URI:http://schema.org/Action>}
{:s=>#<RDF::Node:0x2afcccbc4960(_:b1)>, :p=>#<RDF::URI:0x2afcccbc4604 URI:http://schema.org/name>, :o=>#<RDF::Literal:0x2afcccbc458c("Add to cart")>}
{:s=>#<RDF::Node:0x2afcccbb2db4(_:b0)>, :p=>#<RDF::Vocabulary::Term:0x2afccb3fb658 ID:http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, :o=>#<RDF::URI:0x2afcccbb2d64 URI:http://schema.org/ItemList>}
{:s=>#<RDF::Node:0x2afcccbb2db4(_:b0)>, :p=>#<RDF::URI:0x2afcccbb292c URI:http://schema.org/numberOfItems>, :o=>#<RDF::Literal::Integer:0x2afcccbb2814("4"^^<http://www.w3.org/2001/XMLSchema#integer>)>}
{:s=>#<RDF::Node:0x2afcccbb2db4(_:b0)>, :p=>#<RDF::URI:0x2afcccbb23c8 URI:http://schema.org/itemListOrder>, :o=>#<RDF::Literal:0x2afcccbb2350("Relevance")>}
{:s=>#<RDF::Node:0x2afcccbb2db4(_:b0)>, :p=>#<RDF::URI:0x2afcccbc5f2c URI:http://schema.org/url>, :o=>#<RDF::URI:0x2afcccbc5eb4 URI:https://www.example.com>}
```

**Comment by gkellogg** [comment]
Whats happening is that the Product is being dropped because it's `@id` is a relative IRI, which is not valid RDF. To make this work, you need to give a default base IRI. This is typically done as the location of the document when loading, but can be set/overridden using either `@base` in a context, or with the `base` API option.

The [distiller](http://rdf.greggkellogg.net/distiller?command=serialize&format=jsonld&output_format=turtle&url=http:%2F%2Fexample.com) I mentioned elsewhere doesn't have a default base, but you can set it through a form field.

Add that and you'll get the following triples:

```turtle
@base <http://example.com> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://example.com/123456> a schema:Product;
  schema:image <https://www.example.com/image.jpg>;
  schema:name "Product Name";
  schema:position 1;
  schema:potentialAction [
    a schema:Action;
    schema:name "Add to cart"
  ];
  schema:sku "product-name";
  schema:url <https://www.example.com/product> .

 [
    a schema:ItemList;
    schema:itemListElement <http://example.com/123456>;
    schema:itemListOrder "Relevance";
    schema:numberOfItems 4;
    schema:url <https://www.example.com>
  ] .
```

**Comment by typhoon2099** [comment]
Ah, I hadn't realised that. Is it possible to pass the base URL into either the `SPARQL.parse` method or the `RDF::Graph.new` method? We load the HTML in from files locally, there's no remote access so we don't get the base URL automatically.

**Comment by gkellogg** [comment]
Most libraries accept a `base` or `base_uri` option which is used when parsing docs that may include relative URIs. Typically, these resolve to the location of the document on the Internet, but for form-based solutions, or other purposes, it can be useful to override.

SPARQL.parse delegates to SPARQL::Grammar.parse, which invokes the SPARQL::Grammar::Parser, which has a `base_uri` option. ([Docs](https://rubydoc.info/github/ruby-rdf/sparql/SPARQL/Grammar/Parser) could be improved).

RDF::Graph.new does not parse source, but just creates a place to dump triples. The [Readers](https://rubydoc.info/github/ruby-rdf/rdf/RDF/Reader) (e.g., RDF::Turtle::Reader and JSON::LD::Reader) are used to turn syntax into triples, and they also have a `base_uri` parameter. If you use `RDF::Graph.load`, it should pass this option along.
