### ISSUE TITLE
`JSON::LD::API.toRdf`, when given a Hash as input, may mutate it

### ISSUE THREAD

**Issue by ClearlyClaire** [ruby-rdf/json-ld#54]
When given a hash with an embedded `@context`, it can end up removing `@context` from the nested hash.

This seems to be because of https://github.com/ruby-rdf/json-ld/blob/9fd51e0622ebe5c52c736d56f31ddf74b4eb7bb5/lib/json/ld/expand.rb#L91

**Comment by gkellogg** [comment]
Yes, but I believe this is removing it from a copy of the original input, unless you have a use case that illustrates an actual issue created because of that. That said, the code would probably work using `input['@context']` instead of `input.delete('@context')`.

**Comment by gkellogg** [comment]
I'll get an update out shortly with a fix. Thanks for the use case.

**Comment by gkellogg** [comment]
I pushed a fix to the develop branch. If that solves your issues, I'll push a new release out.

**Comment by ClearlyClaire** [comment]
It does solve it! Thank you for the quick fix!
