### ISSUE TITLE
Blank @id for embedded schema.org JSON-LD in webpage?

### ISSUE THREAD

**Issue by fbacall** [ruby-rdf/json-ld#55]
When extracting JSON-LD from a webpage, the root always seems to be a blank node.

```ruby
graph = RDF::Graph.load('https://training.galaxyproject.org/training-material/topics/assembly/tutorials/debruijn-graph-assembly/tutorial.html', format: :jsonld)
puts graph.dump(:jsonld, validate: false, standard_prefixes: true)
```
=>
```
{
  "@context": {
    "schema": "http://schema.org/",
    "dc": "http://purl.org/dc/terms/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "_:g457280",
      "@type": "schema:LearningResource",
      "dc:conformsTo": {
        "@id": "https://bioschemas.org/profiles/TrainingMaterial/1.0-RELEASE"
      },
...
```
This seems to be the case even if I explicitly set the `base_uri` option.

Is there a way to read in the triples such that the subject is the URL of the page? Or if not, is there a way for me to know what the root node will be so that I can query properties only from the top-level resource?

I've tried various ways of reading in the triples using both the RDFa and JSON-LD readers, from local files and from remote URLs, and with or without the `base_uri` and `base` options set.

**Comment by gkellogg** [comment]
The JSON-LD in that page does not declare an `@id`, so it is implicitly given a blank node as an ID. If you want the document to have the same subject as the enclosing document, add `"@id": ""` to the document near the first `@type`. (Also, use `https://schema.org` as the context, not `http://schema.org`).

If you extract the JSON-LD from your document manually, and paste it into json-ld.org/playground, you'll note the same thing, that it does not have an `@id`, which is equivalent to having a blank nod `@id`.

You should be able to use my distiller (http://rdf.greggkellogg.net/distiller) without needing to install anything, but if you have installed the json-ld gem, you can also use the `rdf` CLI:

```
rdf serialize https://training.galaxyproject.org/training-material/topics/assembly/tutorials/debruijn-graph-assembly/tutorial.html --output-format jsonld
```

This will parse to RDF and then re-serialize as JSON-LD. You can also just uses the `expand` command, instead of `serialize`. Note that it will also complain about some malformed HTML, but that shouldn't affect the results.

**Comment by fbacall** [comment]
So that page isn't one that I manage, but I've generally noticed that the vast majority of JSON-LD schema.org markup does not explicitly declare any kind of `@id` (including the examples on the schema.org website) for the "top level" resource.

What I'm trying to build is a crawler that crawls a sitemap looking for certain schema.org types. I was hoping I could just somehow throw documents at `ruby-rdf` and have it extract whatever RDFa/JSON-LD it finds without having to do any parsing beforehand.

Is the best solution here to extract the content of `<script type="application/ld+json">` tags, add `"@id" : ""` (if `@id` is missing), then send that to the JSON-LD parser (along with `base_uri` or `base`)?

**Comment by gkellogg** [comment]
> So that page isn't one that I manage, but I've generally noticed that the vast majority of JSON-LD schema.org markup does not explicitly declare any kind of `@id` (including the examples on the schema.org website) for the "top level" resource.

Yes, the schema.org examples do not typically encourage the use of `@id`, but that inevitably results in the proliferation of blank nodes.

> What I'm trying to build is a crawler that crawls a sitemap looking for certain schema.org types. I was hoping I could just somehow throw documents at `ruby-rdf` and have it extract whatever RDFa/JSON-LD it finds without having to do any parsing beforehand.

Yes, if you require the ‘linked data’ gem, and you parse tap with the RDF::RDFa parser, it will also look for embedded a micro database, JSON-LD and RDF/XML.

> Is the best solution here to extract the content of `<script type="application/ld+json">` tags, add `"@id" : ""` (if `@id` is missing), then send that to the JSON-LD parser (along with `base_uri` or `base`)?

Try parsing as RDFa, as I mentioned above, that should do all the work for you.

**Comment by fbacall** [comment]
I guess where I'm stuck is where to go from there. I want to extract all the properties of the "top level" `LearningResource` for the above page, without also pulling in the 2 `LearningResource`s that are under the `competencyRequired` of the top one.

My original thought was I could query for
```
[RDF::URI(page_url), RDF.type, RDF::Vocab::SCHEMA.LearningResource]
```
but got stumped by the blank node.

I suppose I could do 2 queries, firstly:
```
[:resource, RDF.type, RDF::Vocab::SCHEMA.LearningResource]
```
and then subtract any matches from:
```
[:resource, RDF.type, RDF::Vocab::SCHEMA.LearningResource]
[:s, :p, :resource]
```

**Comment by fbacall** [comment]
Alright, thanks. I'll go from there. Feel free to close this

**Comment by fbacall** [comment]
Actually, a small, unrelated question... is there a way to silence the errors about malformed HTML?
e.g.
```
728:2: ERROR: That tag isn't allowed here  Currently open tags: html, body, div, section, div, table, tbody, tr, td, span, ul.
 </td>
 ^
```

**Comment by gkellogg** [comment]
Typically, those errors should only be shown when the `validate` option is used. Pic it can be reproduced via the code you provided at the top, I’ll take a look. Otherwise, please give me something to reproduce the issue.

**Comment by fbacall** [comment]
```ruby
require 'linkeddata'
reader = RDF::Reader.for(:rdfa).open('https://training.galaxyproject.org/training-material/topics/assembly/tutorials/debruijn-graph-assembly/tutorial.html')
```
It doesn't seem to happen with `RDF::Graph.load`, but I need to be able to open `File` and other IO-like objects instead of just URLs

**Comment by gkellogg** [comment]
By default, the reader is logging errors to STDERR. You can change this using the `logger` option, either to an instance of `Logger`, an IO, or `false` (really anything that responds to `#write`).

```
RDF::Reader.for(:rdfa).open('https://training.galaxyproject.org/training-material/topics/assembly/tutori
als/debruijn-graph-assembly/tutorial.html', logger: false)
```

The reader does log errors found (as well as other useful information) if errors are found in the document, such as these. The `validate` option simply controls the behavior of the reader in the presence of errors. If set to `true`, it will halt with an `RDF::ReaderError` if errors have been logged.

If you're not concerned with any error reporting, set `logger: false`, or you can capture in a `StringIO` or `logger: Logger.new(StringIO.new)`
